version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: abdhesh
      MONGO_INITDB_ROOT_PASSWORD: Abd%$#!
      MONGO_INITDB_DATABASE: mydb  # Set default database name
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

volumes:
  mongodb_data_container:
